DROP DATABASE IF EXISTS cowlist;
CREATE DATABASE cowlist;

USE cowlist;

DROP TABLE IF EXISTS list;
CREATE TABLE list (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500) NULL DEFAULT NULL,
    PRIMARY KEY (id)
);